config/routes.rb
Rails.application.routes.draw do
  get '/top', to: 'homes#top'
  root to:'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end


  def index
    @books = Book.all
    @book = Book.new
  end

  def create

    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      flash[:alret] = "Failed to post"
      @books = Book.all
      render "index"
    end


  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]= "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      flash[:alret] = "Failed to post"
      @books = Book.all
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
<% end %>
<h1>Editing Book</h1>
<%= form_with model: @book do |f| %>

<div class="field">
 <div class="field_with_errprs">
   <laber for="book_title">Title</label>
  </div>
 <%= f.text_field :title %>
</div>

<div class="field">
  <div class="field_with_errprs">
   <label for="book_body">Body</label>
  </div>
 <%= f.text_area :body %>
</div>
<div class="field">
 <%= f.submit 'Update Book' %>
</div>

 <%= link_to "Show", book_path(@book.id) %>
 |
 <%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div><!DOCTYPE html>

<html>
  <body>
  <h1 class="books">Books</h1>
   <table class="table" cellpadding="3">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
     </tr>
    </thead>
   <tbody>
 <% @books.each do |book| %>
      <tr>
       <td><%= book.title %></td>
       <td><%= book.body %></td>
       <td><%= link_to "Show", book_path(book.id) %></td>
       <td><%= link_to "Edit", edit_book_path(book.id) %></td>
       <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
      </tr>
 <% end %>
   </tbody>
  </table>


<h2>New book</h2>
<%= form_with model: @book do |f| %>
  <% if @book.errors.any? %>
   <%= @book.errors.count %>errors prohibited this book from being saved:
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>


<% end %>


 <div class="field">
  <div class="field_with_errprs">
   <laber for="book_title">Title</label>
  </div>
  <%= f.text_field :title %>
 </div>
 <br>
 <div class="field">
  <div class="field_with_errprs">
   <label for="book_body">Body</label>
  </div>
  <%= f.text_area :body %>
  </div>

 <div class="actions">
    <%= f.submit 'Create Book' %>
 </div>
   <% end %>
 </body>
</html>

app/views/books/show.html.erb
<html>
 <body>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
<strong>Body:</strong>
  <%= @book.body %>
</p>
  <%= link_to "Edit", edit_book_path(@book.id) %>
 |
  <%= link_to "Back", books_path %>


 </body>
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="book.css">
    <title>WebCampBackendNew</title>
</head>
<body>

 <h1>ようこそ Bookersへ!</h1>
    <p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>
    <%= link_to "start", books_path %>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WedCampBackendNew</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="text-success">
    <%= flash[:notice] %>
  </div>


    <%= yield %>

</html>